---
title: "<h1 style='width:100%;font-size:3em;'>Perception of Statistical Graphics</h1>"
author: "<h2 style='width:100%;font-size:2em;'>Susan VanderPlas</h2>"
output: 
  revealjs::revealjs_presentation:
    pandoc_args: [ "--slide-level", "2" ]
    center: false
    transition: fade
    fig_caption: true
    margin: 0.1
    width: 1600
    height: 900
---

<section>
<h1 style="font-size:2em;"> Outline</h1> 
### Sine Illusion
<ul style="margin-bottom:20px;margin-top:10px;width:95%;">
  <li>
    <b>Signs of the Sine Illusion: Why We Need to Care</b>
    <br>Proposes geometry-based transformations and presents data from user study 
    <br><i>(Accepted to JCGS, July 2014)</i>
  </li>
  <li>
    <b>The Curse of Three Dimensions: Why Your Brain is Lying to You</b>
    <br>Examines cause of the illusion (depth perception), provides case study and presents data from another user study 
    <br><i>(Intended for submission to IEEE Transactions on Applied Perception)</i>
  </li>
<ul>

---

<ul style="margin-bottom:20px;margin-top:10px;width:95%;">
  <li>
    <b>Spatial Reasoning and Data Displays</b>
    <br>What visual skills are necessary for lineup evaluation and reading statistical graphics?
    <br><i>(Submitted to IEEE Transactions on Visualization and Computer Graphics, January 2015)</i>
  </li>
  <li>
    <b>Statistical Graphics and the Hierarchy of Visual Features</b>
    <br>What visual features of statistical plots affect the perception of displayed data?
    <br><i>(Intended for submission to the Journal of Computational and Graphical Statistics)</i>
  </li>
</ul>

</section>


```{r sineillusion-setup, fig.keep='all', cache=FALSE, echo=FALSE, include=FALSE, eval=TRUE}
require(knitr)
rm(list=ls())
wd <- getwd()
opts_chunk$set(cache.path='cache/', fig.align='center', fig.width=6, fig.height=6, fig.show='hold', par=TRUE, cache=TRUE, concordance=TRUE, autodep=TRUE, root.dir="../", fig.path='Prelim-figure/', message=FALSE, warning=FALSE)
datadir <- "../Data/sineIllusion/"
codedir <- "../Code/sineIllusion/"
options(replace.assign=TRUE,width=70,scipen=3)
require(knitr)
library(reshape2)
suppressMessages(library(ggplot2))
library(plyr)
suppressMessages(library(gridExtra))

source(paste(codedir, "functions.r", sep=""))

f <- function(x) 2*sin(x)
fprime <- function(x) 2*cos(x)
f2prime <- function(x) -2*sin(x)

```
